// GENERATED by scripts/posts-index.mjs — do not edit by hand.
// Regenerated before every build/dev run. Used by the Edge-runtime
// per-post OG image route, which cannot read content/posts/ itself.

export interface PostIndexEntry {
  slug: string;
  title: string;
  description: string;
  pillar: string;
  readingMinutes: number;
}

export const POSTS_INDEX: PostIndexEntry[] = [];
