// Generates lib/posts-index.generated.ts from content/posts/*.mdx.
//
// Why this exists: the per-post Open Graph image route runs on the Edge
// runtime (the Node build of next/og breaks on Windows and can't be
// statically generated), and Edge has no filesystem. So the metadata the
// card needs — slug, title, description, pillar, reading time — is
// bundled as a plain module instead. Runs automatically before `build`
// and `dev` (see package.json scripts). Committed so a fresh checkout
// type-checks; regenerated on every build so it can't go stale.
//
// Publication rules mirror lib/posts.ts: skip `draft: true` and future
// dates. Keep the two in sync if either changes.

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const postsDir = join(root, "content", "posts");
const outFile = join(root, "lib", "posts-index.generated.ts");

const today = new Date().toISOString().slice(0, 10);
const readingMinutes = (text) =>
  Math.max(1, Math.round(text.split(/\s+/).filter(Boolean).length / 220));

const posts = existsSync(postsDir)
  ? readdirSync(postsDir)
      .filter((f) => f.endsWith(".mdx"))
      .map((f) => {
        const { data, content } = matter(readFileSync(join(postsDir, f), "utf8"));
        if (data.draft === true) return null;
        if (typeof data.date !== "string" || data.date > today) return null;
        return {
          slug: f.replace(/\.mdx$/, ""),
          title: String(data.title ?? "").trim(),
          description: String(data.description ?? "").trim(),
          pillar: String(data.pillar ?? ""),
          readingMinutes: readingMinutes(content),
        };
      })
      .filter(Boolean)
  : [];

const body = [
  "// GENERATED by scripts/posts-index.mjs — do not edit by hand.",
  "// Regenerated before every build/dev run. Used by the Edge-runtime",
  "// per-post OG image route, which cannot read content/posts/ itself.",
  "",
  "export interface PostIndexEntry {",
  "  slug: string;",
  "  title: string;",
  "  description: string;",
  "  pillar: string;",
  "  readingMinutes: number;",
  "}",
  "",
  `export const POSTS_INDEX: PostIndexEntry[] = ${JSON.stringify(posts, null, 2)};`,
  "",
].join("\n");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body);
console.log(`posts-index: ${posts.length} published post(s) → lib/posts-index.generated.ts`);
